# Generated by Django 4.1.3 on 2023-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusermodel',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
